name: Build and deploy to Netlify

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: .NET SDK installeren
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: App bouwen
        run: dotnet publish UrenRegistratie.csproj -c Release -o release

      - name: Naar Netlify sturen
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: 'release/wwwroot'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Automatische publicatie"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
